# Generated by Django 5.2.6 on 2025-12-13 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_product_brand_product_discount_percentage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_host_user', models.CharField(help_text='Your Gmail address (e.g., yourname@gmail.com). Acts as the sender.', max_length=255)),
                ('email_host_password', models.CharField(help_text='Your 16-character App Password. Go to Google Account > Security > 2-Step Verification > App Passwords to generate one.', max_length=255)),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
