# Generated by Django 5.2.6 on 2025-12-13 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='visible_to_customer',
            field=models.BooleanField(default=True, help_text='If false, hides order from customer profile (soft delete)'),
        ),
    ]
