# Generated by Django 5.2.6 manually fixed

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_brand_product_brand_new'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brand_new',
            new_name='brand',
        ),
    ]
