# Generated by Django 5.2.6 on 2025-12-16 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_verificationcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_is_sandbox',
            field=models.BooleanField(default=True, help_text='Enable sandbox mode for testing'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_store_id',
            field=models.CharField(blank=True, help_text='SSLCommerz Store ID (for production use real credentials)', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='sslcommerz_store_pass',
            field=models.CharField(blank=True, help_text='SSLCommerz Store Password', max_length=200),
        ),
    ]
