# Generated by Django 5.2.6 on 2025-12-16 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_sitesettings_sslcommerz_is_sandbox_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('store.order',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Cost of goods (for profit calculation)', max_digits=10),
        ),
    ]
