# Generated by Django 5.2.6 on 2026-01-04 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_accountingentry'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='address',
            field=models.TextField(default='123 Tech Street, Dhaka, Bangladesh', help_text='Physical address'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_email',
            field=models.EmailField(default='support@rbtrading.com', help_text='Public facing contact email', max_length=254),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='contact_phone',
            field=models.CharField(default='+880 1234-567890', help_text='Public contact phone', max_length=20),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='facebook_link',
            field=models.URLField(blank=True, help_text='Facebook Page URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='instagram_link',
            field=models.URLField(blank=True, help_text='Instagram Profile URL'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='RB Trading', max_length=100),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='twitter_link',
            field=models.URLField(blank=True, help_text='Twitter Profile URL'),
        ),
    ]
