# Generated by Django 5.2.6 on 2026-06-22 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0012_sitesettings_address_sitesettings_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_host_password',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='email_host_user',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sslcommerz_is_sandbox',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sslcommerz_store_id',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='sslcommerz_store_pass',
        ),
    ]
